DEFAULT:
  DeviceDataPath: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Devices/Edge_Device/data"
  IntervalDataGenerator: 1
  NumberOfSamplesGenerated: 50
  MessageBrokerHost: "localhost"
  QueueBase: "Queue"
  InputDimension: 9
  OutputDimension: 6
  #NumberOfParticipants: 6
  NumberOfParticipants: 1
  Epochs : 1
  LearningRate: 1000
  Precision: 10000
  WaitingTime: 2
  #BatchSize: 40
  BatchSize: 10
  #Rounds : 300
  Rounds : 30
  TestFilePath: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Devices/Edge_Device/data/test.txt"
  TrainFilePath: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Devices/Edge_Device/data"
  IntervalTime: 40
  PercentOfDataGenerated: 0.0086
  #PerformProof: False
  PerformProof: True
  PerformRegistration: True
  Gas: 100000000000000
  #Gas: 1000000000000

  ResponseVariable: "Activity"
  EtheriumRPCServer: "http://127.0.0.1:8545"
  FLContractAddress: "0x5856458dfB54fC0a1133A98bE83ccaA7D52ECED9"  
  VerifierContractAddress: "0x061e562A4cc9C6B574dEE8CD2f47De6661F1d13e"
  RegisterContractAddress: "0x14Bf2932CB83dc414AF81Ebe610612b8e9337249"  
  RegisterVerifierContractAddress: "0x4E3E5e06818ea43b55071bC8C151625E63340D13"
  ZokratesPath: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Verification/ZoKrates/root.zok"
  VerificationBase: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Verification/SAVED_VERIFYER_10/"
  FLContractABIPAth: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Blockchain/Truffle/build/contracts/FederatedModel.json"
  RContractABIPAth: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Blockchain/Truffle/build/contracts/Registration.json"
  AnalyticsOutBase: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Devices/MiddleWare/Analytics/"
  Activities : [5, 11, 12, 14, 15, 17]
  ActivitiesEncoded : [1,2,3,4,5,6]
  ActivityMappings:
    2: 1
    3: 1
    4: 1
    16: 15
    6: 5
    10: 11
    13: 14
    7: 1
  ActivityEncoding:
    5: 1
    11: 2
    12: 3
    14: 4
    15: 5
    17: 6

TEST:
  ZokratesPath: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Verification/ZoKrates/"
  VerificationBase: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Devices/Authentication/Verification/SAVED_VERIFYER_10/"

Registration:
  ZokratesPath: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/CA/Zokrates/"
  VerificationBase: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/CA/Zokrates"
  