DEFAULT:
  DeviceDataPath: "/home/block/thesis_CHLEE/data"
  IntervalDataGenerator: 1
  NumberOfSamplesGenerated: 50
  MessageBrokerHost: "localhost"
  QueueBase: "Queue"
  InputDimension: 9
  OutputDimension: 6
  NumberOfParticipants: 1
  Epochs : 1
  LearningRate: 1000
  Precision: 10000
  WaitingTime: 2
  BatchSize: 10
  Rounds : 300
  TestFilePath: "/home/block/thesis_CHLEE/data/test.txt"
  TrainFilePath: "/home/block/thesis_CHLEE/data"
  IntervalTime: 40
  PercentOfDataGenerated: 0.0086
  #PerformProof: False
  PerformProof: True
  PerformRegistration: True
  Gas: 100000000000000
  #Gas: 1000000000000

  ResponseVariable: "Activity"
  EtheriumRPCServer: "http://141.223.163.119:8545"
  FLContractAddress: "0xEa9f8A1f91d90E1EC9B5FCe9c7340a3BD2DA5D3F"  
  VerifierContractAddress: "0x56Dc8e8Da72935D9d46c08e0BA207C883AfE1C34"
  RegisterContractAddress: "0xc762502b30019905F01c557b99E17083F8A07D9F"  
  RegisterVerifierContractAddress: "0x2FDc62F33Fd555d49d313718Ea3D45D0cBF805Ad"
  ZokratesPath: "/home/block/thesis_CHLEE/End-to-End-Verifiable-Decentralized-Federated-Learning/Verification/ZoKrates/root.zok"
  VerificationBase: "/home/block/thesis_CHLEE/End-to-End-Verifiable-Decentralized-Federated-Learning/Verification/SAVED_VERIFYER_10/"
  FLContractABIPAth: "/home/block/thesis_CHLEE/End-to-End-Verifiable-Decentralized-Federated-Learning/Blockchain/Truffle/build/contracts/FederatedModel.json"
  RContractABIPAth: "/home/block/thesis_CHLEE/End-to-End-Verifiable-Decentralized-Federated-Learning/Blockchain/Truffle/build/contracts/Registration.json"
  AnalyticsOutBase: "/home/block/thesis_CHLEE/End-to-End-Verifiable-Decentralized-Federated-Learning/Devices/MiddleWare/Analytics/"
  Activities : [5, 11, 12, 14, 15, 17]
  ActivitiesEncoded : [1,2,3,4,5,6]
  ActivityMappings:
    2: 1
    3: 1
    4: 1
    16: 15
    6: 5
    10: 11
    13: 14
    7: 1
  ActivityEncoding:
    5: 1
    11: 2
    12: 3
    14: 4
    15: 5
    17: 6

TEST:
  ZokratesPath: "/home/block/thesis_CHLEE/End-to-End-Verifiable-Decentralized-Federated-Learning/Verification/ZoKrates/"
  VerificationBase: "/home/block/thesis_CHLEE/End-to-End-Verifiable-Decentralized-Federated-Learning/Verification/SAVED_VERIFYER_10/"

Registration:
  ZokratesPath: "/home/block/thesis_CHLEE/End-to-End-Verifiable-Decentralized-Federated-Learning/CA/Zokrates/"
  VerificationBase: "/home/block/thesis_CHLEE/End-to-End-Verifiable-Decentralized-Federated-Learning/CA/Zokrates"
  
