DEFAULT:
  DeviceDataPath: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Devices/Edge_Device/data"
  IntervalDataGenerator: 1
  NumberOfSamplesGenerated: 50
  MessageBrokerHost: "localhost"
  QueueBase: "Queue"
  InputDimension: 9
  OutputDimension: 6
  #NumberOfParticipants: 6
  NumberOfParticipants: 2
  Epochs : 1
  LearningRate: 1000
  Precision: 10000
  WaitingTime: 2
  #BatchSize: 40
  BatchSize: 10
  #Rounds : 300
  Rounds : 25
  TestFilePath: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Devices/Edge_Device/data/test.txt"
  TrainFilePath: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Devices/Edge_Device/data"
  IntervalTime: 40
  PercentOfDataGenerated: 0.0086
  #PerformProof: False
  PerformProof: True
  Gas: 100000000000000
  #Gas: 1000000000000

  ResponseVariable: "Activity"
  EtheriumRPCServer: "http://127.0.0.1:8545"
  FLContractAddress: "0xda6C4FfEB79F07DB652F9dfdFf78F3B956250BF6"  
  VerifierContractAddress: "0x242917730A77F872A6434a08D3F541C1A65d21B0"
  ZokratesPath: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Verification/ZoKrates/root.zok"
  VerificationBase: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Verification/SAVED_VERIFYER_10/"
  FLContractABIPAth: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Blockchain/Truffle/build/contracts/FederatedModel.json"
  AnalyticsOutBase: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Devices/MiddleWare/Analytics/"
  Activities : [5, 11, 12, 14, 15, 17]
  ActivitiesEncoded : [1,2,3,4,5,6]
  ActivityMappings:
    2: 1
    3: 1
    4: 1
    16: 15
    6: 5
    10: 11
    13: 14
    7: 1
  ActivityEncoding:
    5: 1
    11: 2
    12: 3
    14: 4
    15: 5
    17: 6

TEST:
  ZokratesPath: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Verification/ZoKrates/"
  VerificationBase: "/Users/chaehyeon/Documents/DPNM/2023/TUB/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Devices/Authentication/Verification/SAVED_VERIFYER_10/"
  